### ISSUE TITLE
Video 22 11:52 skips over adding Head to PaginationStyles

### ISSUE THREAD

**Issue by papascott** [wesbos/Advanced-React#20]
At 11:52 in components/Pagination.js `<PaginationStyles>` is moved into the `return()`

At 11:53 there is suddenly a `<Head> `and  `const page = props.page` in the return and an `import Head…` at the top of the file.

A brief explanation would be nice. 😄

**Comment by wesbos** [comment]
Fixed this - I cut out too much on that edit - its added back in now :)
