### ISSUE TITLE
Video 6: 10:43, fade-in cuts off one word

### ISSUE THREAD

**Issue by scallemang** [wesbos/Advanced-React#21]
Not a major thing, just a polish thing. Worth fixing? 🤷‍♀️

First word of your punch-in is a bit cut off. If your footage/audio allows it, maybe play around with that fade-in.

**Comment by dmetivier** [comment]
Something to add to this issue beginning at 00:40. You begin explaining what the "cascading" part of CSS means and get a little tripped up with words. A few seconds after you begin explaining that part again. I'm sure this is meant to be edited out 😄

**Comment by wesbos** [comment]
thanks! both fixed
