### ISSUE TITLE
Transcripts

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#24]
A Feature Request:

Something that would be really useful imho, would be to have transcripts for the videos.

It would be a huge help in reviewing the course to be able to locate all the areas where "Apollo" or "cache", "resolver", etc. are mentioned.

**Comment by n-hare** [comment]
If I recall on Slack it was mentioned that transcripts would be made after the debugging/beta phase. In case a video needed edited then the transcripts would only need to be made once.

**Comment by wesbos** [comment]
Yep transcripts are coming, but I'm also looking at how to make them searchable int the future too . :)

**Comment by gihrig** [comment]
> but I'm also looking at how to make them searchable int the future too . :)

Great news! The ability to search transcripts is the main reason for having them IMO.
