### ISSUE TITLE
Video #18 clarify instructions

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#29]
Another minor point...

In video #18 at 8:25 you enter an image name to be uploaded. There's a flicker in the video, which I mistakenly took for a form submit. Of course submitting the form redirects to the `items` page.

While this was a dumb user error, it took me a few minutes to overcome the confusion ;-)

If you could simply add "don't submit" after "upload an image" at 8:25, that would prevent others from making the same dumb mistake.

**Comment by wesbos** [comment]
👌 thanks!
