### ISSUE TITLE
Video #19 Inconsistent API?

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#30]
Video 19 at 6:37

In resolver/Mutation.js you return a promise from `updateItem`, whereas in `createItem`, just above, you await the resolution of that promise and return that.

Is this intentional? Why the different approach? Feels more consistent to have a similar return value (promise vs result) for all mutations.

Am I missing something?

**Comment by wesbos** [comment]
I explain this a little later in the video - resolvers can either return a promise or values directly. 

There are no benefits one way or another, just sometimes you need to massage the queried data before returning it from a resolver
