### ISSUE TITLE
Title bar color

### ISSUE THREAD

**Issue by tomitrescak** [wesbos/Advanced-React#31]
Hi, this should probably go to vscode, but I was wondering how you made the title bar change color. To me it stays always grey on vscode mac 1.27.2

**Comment by gihrig** [comment]
Have a look at `.vscode/settings.json` in the example project. You should have this in your `WORKSPACE SETTINGS` section for a gold title bar:

```json
{
  "workbench.colorCustomizations": {
    "titleBar.activeForeground": "#000",
    "titleBar.inactiveForeground": "#000000CC",
    "titleBar.activeBackground": "#FFC600",
    "titleBar.inactiveBackground": "#FFC600CC"
  }
}
```

**Comment by tomitrescak** [comment]
It’s there:/

**Comment by gihrig** [comment]
Yeah, check with VS Code. I'm running VS Code mac 1.27.2 as well and it works for me.

**Comment by tomitrescak** [comment]
Found it ... `window.nativeTabs` break the functionality.
