### ISSUE TITLE
Video #19 Possible FAQ item

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#33]
Video #19 A new file `UpdateItem.js` is created and modified from 7:05 to 8:23, here `createItem()` is left in.

```javascript
   createItem(
     title: $title
     description: $description
     price: $price
   )
```
`createItem()` should be renamed to `updateItem()`

It would help to clarify things to have `createItem()` updated at @8:23 when the original file changes are being made.

FAQ item: Don't worry about this, Wes collides head on with this and works through troubleshooting from @22:47-24:38. "And there was much rejoicing!" 😄

**Comment by wesbos** [comment]
thanks a ton!
