### ISSUE TITLE
Video #20 feature request

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#39]
The technique demonstrated in video #20 is dependent on a server response for a UI update.
For example, setting Chrome -> Devtools -> Network -> Throttling to "Slow 3G" results in a delay of a few seconds before the UI updates.

I am working on a project that uses drag and drop to organize items. Here a few second delay between dropping an item and updating the UI results user confusion.

In this case I have worked out an (overly?) complex scheme to manually update the cache using `client.readFragment` and `client.writeFragment` in addition to updating the server using `client.mutate()`. The result is about 650 lines of code, and I'm having problems keeping the server, cache and UI in sync.

I've thought about [options.fetchPolicy](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-fetchPolicy) settings, but these seem to only apply to reading the cache, not writing.

`cache.writeFragment` looks promising, I'll play around with that, but if anyone has ideas or examples that would be wonderful!

The code shown in video #20 is so simple! It would be really cool if the cache could be updated instantly without waiting for a server response.

**Comment by n-hare** [comment]
Maybe Optimistic UI/Response, from the Apollo docs,

> As explained in the mutations section, optimistic UI is a pattern that you can use to simulate the results of a mutation and update the UI even before receiving a response from the server. Once the response is received from the server, the optimistic result is thrown away and replaced with the actual result.

[https://www.apollographql.com/docs/react/features/optimistic-ui.html#optimistic-basics](url)

**Comment by wesbos** [comment]
Yes I show optimistic response later in the course :)
