### ISSUE TITLE
Video #62 — testUtils.js has id for fakeItem

### ISSUE THREAD

**Issue by scrumptiousdev** [wesbos/Advanced-React#44]
**Files:** CreateItem.test.js and testUtils.js
**Video #62:** 24:35

On 24:35, test fails because `id` was originally missing from `fakeItem` in testUtils.js.
Wes wrote `id: 'abc123'` to fix the problem but the starter file is fixed with `id` for `fakeItem` in testUtils.js, which leads to another error since its id is set to `'123'` in the testUtils.js.

Either in video or starter file needs an update :)

CreateItem.test.js
```javascript
it('creates an item when the form is submitted', async () => {
    ...
	
    const mocks = [{
        ...
        result: {
            data: {
                createItem: {
                    id: 'abc123'
                    __typename: 'Item',
                    ...fakeItem()
                }
            }
        }
    }];
});
```

testUtils.js
```
const fakeItem = () => ({
  __typename: 'Item',
  id: '123',
  price: 5000,
  user: null,
  image: 'dog-small.jpg',
  title: 'dogs are best',
  description: 'dogs',
  largeImage: 'dog.jpg',
});
```

**Comment by wesbos** [comment]
fixed! thanks a ton
