### ISSUE TITLE
Video #14: 18:03 - prismia.graphql playground errors

### ISSUE THREAD

**Issue by cnewfeldt** [wesbos/Advanced-React#55]
I'm not sure if this is an issue per se, but I seemed to have deployed the User from the datamodel and it polluted my prisma.graphql file. 

I'm not 100% sure to be exact, but following your steps I started seeing the following error that differed from the one you found at your createAt (missing the d, btw) issue at 17:24:

My User error:

`{
  "data": null,
  "errors": [
    {
      "message": "Variable \"$_v0_data\" got invalid value {\"title\":\"test\",\"description\":\"Testing 123\",\"price\":100,\"image\":\"dog.jpg\",\"largeImage\":\"doggggg.jpg\"}; Field value.user of required type UserCreateOneInput! was not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createItem"
      ]
    }
  ]
}`

I tried uncommenting and commenting out #user from the datamodel and running a number of deploys to see if this would clear the issue, but the same error above was returned. 

Next I selected  'UserCreateOneInput' from the error and searched with in the prisma.graphql generated file and found two references. I removed `user: UserCreateOneInput!` from  

`input ItemCreateInput {
  title: String!
  description: String!
  image: String
  largeImage: String
  price: Int!
  user: UserCreateOneInput!
}`

and all of 

`input UserCreateOneInput {
  create: UserCreateInput
  connect: UserWhereUniqueInput
}`

After these removals I was then able to reproduce a successful item creation and continue on with the video. I hope this helps someone. Seems if you get out of step with the prisma.graphql generated file you can cause yourself some migration issues as the file seems to retain any previous missteps.

c

**Comment by wesbos** [comment]
thanks for the heads up - IM not sure why this happened to you but ill keep an ear open for anyone else who this happens to
