### ISSUE TITLE
Sign Out Font is Incorrect

### ISSUE THREAD

**Issue by ssmith-wombatweb** [wesbos/Advanced-React#65]
The font for the sign out button is why it still doesn't look quite the same. It is getting the system-ui font instead of radnika_next.

**Comment by wesbos** [comment]
I think buttons need to explicitly have their font set - will fix

**Comment by ssmith-wombatweb** [comment]
Yeah, adding it to the NavStyles file fixed it for the Nav.

**Comment by wesbos** [comment]
thanks again
