### ISSUE TITLE
Video #30 Frontend Password Reset Flow - Confusion on auto sign in on password reset.

### ISSUE THREAD

**Issue by ssmith-wombatweb** [wesbos/Advanced-React#67]
On Video #30 Frontend Password Reset Flow the way the auto sign in after resetting passwords is described is kinda confusing. At first it seems like we already implemented that but and then it seems to jump and then you start talking about how to implement it.

**Comment by ssmith-wombatweb** [comment]
The description starts at about 11:30.

**Comment by gihrig** [comment]
@ssmith-wombatweb This sequence seems clear to me. Could you add more detail about what is not clear?

**Comment by wesbos** [comment]
Thanks - I'm happy with the description so far : )
