### ISSUE TITLE
Video #28 - Sign Out Button Styling

### ISSUE THREAD

**Issue by LTTaylor** [wesbos/Advanced-React#73]
In video 28 to resolve the issue @ 4m14s with the styling of the button font being different you just need to change the font for buttons as it will be using the default browser styles (eg. on Chrome for windows it sets it to display as Arial).

This can be resolved by adding a `font-family: inherit` to the button styles in `NavStyles.js`.

**Comment by wesbos** [comment]
thanks :) Already fixed this one
