### ISSUE TITLE
Video #36 - bug?

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#76]
I ran into a problem in Video #36. @14:08 the "inactive+Updating" feature of the Update button is demonstrated.

Problem/bug?

In my code this works as far as deactivating the button and changing the button text is concerned, but the visual change happens to all displayed buttons, not just the one clicked as shown in the video.

My code compares well with the "Finished Application" code, so I thought I would setup the finished app and see how that worked. 

I ran into problems setting up the finished application, see #77

**Comment by wesbos** [comment]
thanks - i haven't heard from anyone else getting this but let me know if you have your code example.
