### ISSUE TITLE
Video #36 auto-submit bug

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#78]
Toward the end of video #36 a method is discussed to automatically update permission changes when the checkbox is clicked.

@16:45 the code is modified to call `updatePermissions()`. This does not update the database with the changed permission. The call is made but the updated state is not available at the time `updatePermissions` is called.

Fortunately, there is a simple solution. `setState` takes an optional callback. When the callback is used the database is updated as expected.

Wrong: As presented in the video:

```javascript
    this.setState({ permissions: updatedPermissions });
    updatePermissions();
```

Working: uses `setState` callback:

```javascript
    this.setState(
      { permissions: updatedPermissions },
      updatePermissions,
    );
```

I have been stumped as to how to achieve this kind of feature in the past.

Thanks Wes, for the cool 'extra'. This is the kind of thing that makes your courses really special!

**Comment by wesbos** [comment]
goood call! I just added a few mins on setState callbacks :)
