### ISSUE TITLE
Video #37 editing confusion ends in error

### ISSUE THREAD

**Issue by gihrig** [wesbos/Advanced-React#80]
Video #37 @5:42 has the correct code:

```javascript
if (!ownsItem && !hasPermission) {
  throw new Error("You don't have permission to do that!")
}
```

Then over the course of the next few seconds an editing error occurs (screen jumps to end of file and returns - You say "oops!") and the last few edit keystrokes are repeated, but the code ends with a logical error:

```javascript
if (!ownsItem && hasPermission) {
  throw new Error("You don't have permission to do that!")
}
```
`hasPermission` should have a 'bang' in front of it:
```javascript 
!hasPermission
```

This error is corrected in the finished application, but the video ends with the error in place.

**Comment by wesbos** [comment]
thanks! Fixed
