### ISSUE TITLE
Video # 55 @ ~16:02

### ISSUE THREAD

**Issue by kalm42** [wesbos/Advanced-React#82]
The last `formatMoney` test hits a real edge case. JavaScript rounds your number.

Line 21, of `frontend/__tests__/formatMoney.test.js`
```
expect(formatMoney(20893749823749823749)).toEqual('$208,937,498,237,498,240.00');
```
...3749 is rounded to ...4000 and the cents are not left off the dollar. I assume this has to do with integer limits in JavaScript. I really am just guessing at why this happened. I'd love an explanation of what happened because I'm a nerd.

**Comment by wesbos** [comment]
:D thank you @gihrig 

Kind of an amazing little lesson on both unit testing and numbers in JavaScript :D
