### ISSUE TITLE
Video #18 - Cloudinary

### ISSUE THREAD

**Issue by esausilva** [wesbos/Advanced-React#85]
Cloudinary changed the **Upload Preset** screen, now it is divided into different tabbed sections, as opposed to one large page as the video shows. I took me a few clicks to find the right tab and proceed to edit the incoming transformations. Around minute 2 of the video

**Comment by scallemang** [comment]
I think most of the UI stuff is in vid. 18 more than 17, right?

**Comment by esausilva** [comment]
Oh, soot. I meant to say Video 18. My bad 🤦‍♂️

**Comment by wesbos** [comment]
fixed!
